#!/usr/bin/env bash

readonly TMP_DIR=$(mktemp -d /tmp/javascript-externs-generator.XXXXXX)
readonly REPO=git@github.com:jmmk/javascript-externs-generator.git
readonly GIT="git -C ${TMP_DIR}"
readonly COMMIT_MSG="Update to latest build"

log() {
  echo "deploy: $1"
}

main() {
  log "lein clean"
  lein clean

  log "Compile to Javascript"
  lein cljsbuild once release

  log "Clone ${REPO}"
  git clone -q "${REPO}" "${TMP_DIR}"

  log "Checkout gh-pages"
  $GIT checkout -q gh-pages

  log "Copy compiled javascript"
  cp out-adv/javascript_externs_generator.min.js "${TMP_DIR}/javascripts"

  log "Commit: ${COMMIT_MSG}"
  $GIT add -A
  $GIT commit -q -m "${COMMIT_MSG}"

  log "Push gh-pages"
  $GIT push -q origin gh-pages

  log "Remove temp directory"
  rm -rf "${TMP_DIR}"
}

main "${@}"
