#!/usr/bin/env bash
set -e

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly TMP_DIR=$(mktemp -d /tmp/javascript-externs-generator.XXXXXX)
readonly REPO=git@github.com:jmmk/javascript-externs-generator.git
readonly GIT="git -C $TMP_DIR"
readonly COMMIT_MSG="Update to latest build"

log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') | Deploy NPM: $1"
}

main() {
  # Move to main project directory
  cd "$DIR/.."

  log "lein clean"
  lein clean

  log "Compile to Javascript"
  lein cljsbuild once release-npm

  log "Clone $REPO"
  git clone -q "$REPO" "$TMP_DIR"

  log "Checkout npm branch"
  $GIT checkout -q npm

  log "Remove old files"
  rm -rf "$TMP_DIR/bin"
  rm "$TMP_DIR/package.json"

  log "Copy new files"
  cp -r bin "$TMP_DIR"
  cp package.json "$TMP_DIR"

  log "Commit: $COMMIT_MSG"
  $GIT add -A
  $GIT commit -q -m "$COMMIT_MSG"

  update_type=""
  while true; do
    read -p "Is this a major, minor, or patch release? " update_type
    if [[ $update_type =~ ^(major|minor|patch)$ ]]; then
      break
    fi

    echo "Invalid update type. Must be one of: major | minor | patch" >&2
    echo ""
  done

  log "Bump version"
  pushd "$TMP_DIR"
  npm version $update_type
  popd

  log "Push npm branch"
  $GIT push -q origin npm

  log "Copy package.json back"
  cp "$TMP_DIR/package.json" "$DIR/package.json"
  git add package.json
  git commit -q -m "Update package.json"
  git push -q origin master

  log "Publish to npm"
  pushd "$TMP_DIR"
  npm publish
  popd -

  log "Remove temp directory"
  rm -rf "$TMP_DIR"
}

main "$@"
