#!/usr/bin/env bash

readonly DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly TMP_DIR=$(mktemp -d /tmp/javascript-externs-generator.XXXXXX)
readonly REPO=git@github.com:jmmk/javascript-externs-generator.git
readonly GIT="git -C $TMP_DIR"
readonly COMMIT_MSG="Update to latest build"

log() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') | Deploy: $1"
}

main() {
  # Move to main project directory
  cd "$DIR/.."

  log "lein clean"
  lein clean

  log "Compile to Javascript"
  lein cljsbuild once release

  log "Clone $REPO"
  git clone -q "$REPO" "$TMP_DIR"

  log "Checkout gh-pages"
  $GIT checkout -q gh-pages

  log "Remove old assets"
  rm -rf "$TMP_DIR/assets"

  log "Copy new assets"
  cp -r assets "$TMP_DIR"

  log "Copy index.html"
  cp index.html "$TMP_DIR"

  log "Commit: $COMMIT_MSG"
  $GIT add -A
  $GIT commit -q -m "$COMMIT_MSG"

  log "Push gh-pages"
  $GIT push -q origin gh-pages

  log "Remove temp directory"
  rm -rf "$TMP_DIR"
}

main "$@"
